### ISSUE TITLE
no matching handler

### ISSUE THREAD

**Issue by pszumelda** [mike01/pypacker#50]
I am writing some pcap reader 

```
from pypacker import ppcap

for ts, buf in preader:
    cache.manager(buf, ts)
```

Unfortunatelly for some pcaps I am getting 

```
Traceback (most recent call last):
  File "C:/Users/p001/PycharmProjects/pyprobe/pcapreader.py", line 20, in <module>
    preader = ppcap.Reader(filename="ez.pcap")
  File "C:\Python\Python3.7.3\lib\site-packages\pypacker\ppcap.py", line 305, in __init__
    super().__init__(filename, PcapHandler.MODE_READ, **initdata)
  File "C:\Python\Python3.7.3\lib\site-packages\pypacker\ppcap.py", line 239, in __init__
    raise Exception("no matching handler found")
Exception: no matching handler found
```

Thanks,
Pawe

**Comment by mike01** [comment]
Hi, thanks for your message. This respository has become staled due to relocation to GitLab (see main page of this repository). Visit https://gitlab.com/mike01/pypacker for up-to-date versions.
